name: manual get repo

on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: install needed soft and run build
        run: |
          git clone -b v1 https://${{ secrets.PESONAL_TOKEN }}@github.com/SpiderDAO/unit-tests.git
          ls -lhF
          cd unit-tests
          pwd
          ls -lhF
