name: manual get DAO repo

on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://${{ secrets.PESONAL_TOKEN }}@github.com/SpiderDAO/unit-tests.git
          pwd
          ls -lhF
          cd unit-tests
          git status
